version: "3.9"
services:
  db:
    image: mysql:latest
    container_name: toyo-db
    environment:
      MYSQL_ROOT_PASSWORD: "dG95byBkYXRhYmFzZQ=="
      MYSQL_DATABASE: "toyo_dev_db"
    ports:
      - "3308:3306"
    volumes:
      - toyo-mysql:/var/lib/mysql
    networks:
      - toyo-network

  api:
    build: .
    container_name: toyo-backend
    environment:
      Json_Folder: "/tmp/toyoverse/"
      ConnectionStrings__DefaultConnection: "server=toyo-db;port=3306;database=toyo_dev_db;user=root;password=dG95byBkYXRhYmFzZQ==;Persist Security Info=False"
      Timeout_Swap_Milliseconds: 30000
      Swap_Interval_Milliseconds: 1000
      chain_id: 80001
      Jwt_Secret: "akasl123990as8dasaqdlkqwe012312kklasda0sd09123lkasksd09"
      Jwt_Expiring_Time_Minutes: 20
      Jwt_RefreshToken_Expires: 20
    volumes:
      - /tmp/toyoverse:/tmp/toyoverse
    ports:
      - "80:80"
      - "443:443"
    networks:
      - toyo-network
    depends_on:
      - db
  
networks:
  toyo-network:

volumes:
  toyo-mysql: