version: "3.9"
services:
  backend-toyo:
    build: .
    command: sh -c "./home/scriptDocker.sh"
    volumes:
      - /tmp/toyoverse:/tmp/toyoverse
    ports:
      - "80:80"
      - "443:443"
      - "5000:5000"
      - "5001:5001"