version: "3.9"
services:
  db:
    image: mysql:latest
    container_name: toyo-db
    environment:
      MYSQL_ROOT_PASSWORD: "dG95byBkYXRhYmFzZQ=="
      MYSQL_DATABASE: "toyo_dev_db"
    ports:
      - "3308:3306"
    volumes:
      - toyo-mysql:/var/lib/mysql
    networks:
      - toyo-network

  api:
    build: .
    container_name: toyo-backend
    environment:
      Toyo_Json_Folder: "/tmp/toyoverse/"
      Toyo_ConnectionStrings__DefaultConnection: "server=localhost;port=3308;database=toyo_dev_db;user=root;password=dG95byBkYXRhYmFzZQ==;Persist Security Info=False"
    volumes:
      - /tmp/toyoverse:/tmp/toyoverse
    ports:
      - "80:80"
      - "443:443"
      - "5000:5000"
      - "5001:5001"
    networks:
      - toyo-network
    depends_on:
      - db
  
networks:
  toyo-network:

volumes:
  toyo-mysql: