version: "3.9"
services:
  api:
    build: .
    container_name: toyo-backend
    image: toyobackend:${TAG}
    environment:
      - ASPNETCORE_ENVIRONMENT
      - ConnectionStrings__DefaultConnection
      - Json_Folder
      - Timeout_Swap_Milliseconds
      - Swap_Interval_Milliseconds
      - Chain_Id
      - Jwt_Secret
      - Jwt_Expiring_Time_Minutes
      - Jwt_RefreshToken_Expires
    volumes:
      - /tmp/toyoverse:/tmp/toyoverse
    ports:
      - "80:80"
      - "443:443"
    networks:
      - toyo-net

networks:
  toyo-net: