setx Toyo_ConnectionStrings__DefaultConnection "server=localhost;port=3308;database=toyo_dev_db;user=root;password=dG95byBkYXRhYmFzZQ==;Persist Security Info=False"
setx Toyo_Json_Folder "C:/temp/toyoverse"
setx Toyo_Timeout_Swap_Milliseconds "4000"
setx Toyo_Swap_Interval_Milliseconds "1000"
setx Toyo_Chain_Id "80001"